### ISSUE TITLE
Issue with MRI 1.9.3

### ISSUE THREAD

**Issue by kirs** [leonid-shevtsov/vydumschik#1]
/Users/Kir/.rvm/gems/ruby-1.9.3-p0@app/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require': /Users/Kir/.rvm/gems/ruby-1.9.3-p0@app/gems/vydumschik-0.0.4/lib/vydumschik/lorem.rb:22: invalid multibyte char (US-ASCII) (SyntaxError)
/Users/Kir/.rvm/gems/ruby-1.9.3-p0@app/gems/vydumschik-0.0.4/lib/vydumschik/lorem.rb:22: invalid multibyte char (US-ASCII)
/Users/Kir/.rvm/gems/ruby-1.9.3-p0@app/gems/vydumschik-0.0.4/lib/vydumschik/lorem.rb:22: syntax error, unexpected $end, expecting keyword_end
    CONSONANTS = %w(б в г д ж з й к л м ?...```

**Comment by kirs** [comment]
I think we should add `#encoding: utf-8` to `lib / vydumschik / lorem.rb` file. I will make a pull request later today.

**Comment by leonid-shevtsov** [comment]
Better later than never - version 0.2.0 is completely compatible with 1.9
